version: '3.9'
services:
  vercel-function:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/workspaces/vercel-function
      - vercel-function-volume:/workspaces/vercel-function/node_modules
volumes:
  vercel-function-volume: